require("zbindenren.options")
require("zbindenren.keymaps")
require("zbindenren.plugins")
require("zbindenren.colorscheme")
require("zbindenren.cmp")
require("zbindenren.whichkey")
require("zbindenren.lsp")
require("zbindenren.telescope")
require("zbindenren.treesitter")
require("zbindenren.autopairs")

require("markdown")
