function update-node-certs --description "Combine macOS System Keychain + Homebrew Mozilla CAs into ~/.node-extra-certs.pem"
    set cert_file $HOME/.node-extra-certs.pem
    set mozilla_bundle /opt/homebrew/etc/ca-certificates/cert.pem

    echo "→ Extracting certificates from macOS System keychain..."
    set keychain_certs (security find-certificate -a -p /Library/Keychains/System.keychain 2>/dev/null)

    echo "→ Writing $cert_file ..."
    begin
        echo "# Combined CA bundle: macOS System Keychain + Homebrew Mozilla CAs"
        echo "# Generated by update-node-certs on "(date)
        echo ""
        echo "# ── macOS System Keychain ──"
        printf "%s\n" $keychain_certs
        echo ""
        if test -f $mozilla_bundle
            echo "# ── Homebrew Mozilla CA bundle ──"
            cat $mozilla_bundle
        else
            echo "# WARNING: Homebrew Mozilla bundle not found at $mozilla_bundle" >&2
            echo "# Install with: brew install ca-certificates" >&2
        end
    end > $cert_file

    set written (grep -c "BEGIN CERTIFICATE" $cert_file)
    echo "✓ Done. Written $written certificates to $cert_file"
end
