[package]
disabled = false

[status]
style = "bg:blue"
symbol = "🔴"
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[directory]
truncate_to_repo = false
truncation_length = 10

[nodejs]
disabled = true

[golang]
disabled = true

[username]
format = "[$user]($style) "

[hostname]
ssh_only = true
format =  "on [$hostname](green) "
